version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:latest

jobs:
  terraform-apply:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

  destroy-approval:
    steps:
      - run:
          name: waiting for approval
          command: echo "waiting for approval" 
  
  terraform-destroy:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform destroy
          command: terraform destroy -auto-approve


workflows:
  version: 2
  deploy_infra:
    jobs:
      - terraform-apply
      - destroy-approval:
          type: approval
      - terraform-destroy:
          requires:
            - destroy-approval
 
